server:
  port: 9930
spring:
  application:
    name: zuul
zuul:
  routes:
    #配置两个映射
    api-a:
      path: /api-a/**
      serviceId: feign
    api-b:
      path: /api-b/**
      serviceId: ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka/