spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git地址
          uri: https://github.com/HeavenElegy/General_Setting
          #搜索目录
          search-paths:
          #登陆账号
          username:
          #登陆密码
          password:
server:
  port: 9940
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka/